### ISSUE TITLE
CumulusRDF logo 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agazzarini/cumulusrdf#60]
```
Make a nice logo, e.g., used as a favicon in the CumulusRDF WebGUI ...
```

Original issue reported on code.google.com by `andreas.josef.wagner` on 20 Apr 2014 at 1:48

**Comment by agazzarini** [comment]
![logo_1](https://cloud.githubusercontent.com/assets/7569632/9528013/c54e198e-4cf2-11e5-864a-eb1f92433ee4.png)
